version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - pip install -r requirements.txt
      - python -m pytest
      - docker build -t 179210174160.dkr.ecr.us-east-1.amazonaws.com/foxtracker .
      - docker push 179210174160.dkr.ecr.us-east-1.amazonaws.com/foxtracker
      - echo Build ended on `date`
